config/routes.rb
Rails.application.routes.draw do

  get '/oauth/callback', to: 'sessions#create'
    resources :pages, only: [:new, :index] do
         collection do
           get 'get_token'
         end
    end
  root 'pages#new'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def new	

	end

	def create

	end

	def get_token
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	
       if(!params[:code].present?)
         p "-----------#{params['client_id']}------------------------------"
         session[:client_id]=params['client_id']
         p "-----------#{session['client_id']}------------------------------"
         session[:client_secret]=params['client_secret']
         redirect_to pages_path(params)
       else
         p "............Else..................."
         p"#{session[:client_id]}--------#{session[:client_secret]}"
         p "#{params[:code]}"
         p "................................................"
         req_params = "client_id=#{session[:client_id]}&client_secret=#{session[:client_secret]}&code=#{params[:code]}&grant_type=authorization_code&redirect_uri=#{ENV['oauth_redirect_uri']}"
         response = JSON.parse RestClient.post("http://localhost:3000/oauth/token", req_params)
         params[:access_token] = response['access_token']
         redirect_to pages_path(params)
      end
  end

  def put_oauth_token
  	  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def new_oauth_token_path(params)
		p "#{ENV['server_base_url']}/oauth/authorize?client_id=#{params['client_id']}&redirect_uri=#{ENV['oauth_redirect_uri']}&response_type=code"
	  "#{ENV['server_base_url']}/oauth/authorize?client_id=#{params['client_id']}&redirect_uri=#{ENV['oauth_redirect_uri']}&response_type=code"
	end
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth2Client</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Welcome!</h1>
<p><%#= link_to 'Authorize via Auth2', url %></p>

<% if params[:access_token] %>
<%#=session[:access_token]%>
  <p><%= link_to 'Get User', "http://localhost:3000/api/user?access_token=#{params[:access_token]}" %></p>
  <p><%= link_to 'Update User', "http://localhost:3000/api/user/update?access_token=#{params[:access_token]}" %></p>
<% else %>
  <p><%= link_to 'Authorize', new_oauth_token_path(params) %></p>
<% end %>

app/views/pages/new.html.erb
<h1> Generate Form</h1>
<%= form_tag oauth_callback_path, method: 'get' do |f| %>
	<p>Application Id: <input type="text" id="client_id" name="client_id"></p>
	<p>Secret:<input type="text" id="client_secret" name="client_secret"></p> 
	<!--<p>Code:<input type="text" id="code" name="code"></p> -->
	<p><button type="submit">Generate</button></p>
<%end%>